course/urls.py
from django.urls import path
from .views import CourseCreateView
urlpatterns = [
    path('create-course/', CourseCreateView.as_view(), name='create'),
]

schoolmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from course.views import dashboard

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard, name='dashboard'),
    path('', include('course.urls')),
    path('', include('student.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
]

admin.site.site_header = "Green Sprouts Admin"
admin.site.site_title = "Green SProuts Management Portal"
admin.site.index_title = "Welcome to Green Sprouts Management Portal"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models

from django.utils.text import slugify
from django.urls import reverse
# Create your models here.

CLASS_CHOICES = (
    ('All Classes ', 'All Classes'),
    ('Junior Class ', 'Junior Class'),
    ('JSS 1 ', 'JSS 1'),
    ('JSS 2', 'JSS 2'),
    ('JSS 3', 'JSS 3'),
    ('Senior Class', 'Senior Class'),
    ('SSS 1', 'SSS 1'),
    ('SSS 2', 'SSS 2'),
    ('SSS 3', 'SSS 3')
)

class Class(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name
    

class Course(models.Model):
    name = models.CharField(max_length=120)
    select_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True)
    course_code = models.CharField(max_length=120, default='001', unique=True)
    slug = models.SlugField(
        default='',
        editable=False,
        max_length=120,
    )
    date_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
      

    class Meta:
        unique_together = ('name', 'slug')

    # def get_absolute_url(self):
    #     kwargs = {
    #         'slug': self.slug
    #     }
    #     return reverse('course_detail', kwargs=kwargs)

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

course/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Course

User = get_user_model()

class CourseUpdateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = [
            'name', 
            'select_class'
            ]

course/views.py
from django.shortcuts import render
from django.urls import reverse
from .models import Course, Class
from .forms import CourseUpdateForm
from .utils import id_generator
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, DetailView
from django.contrib.auth.decorators import login_required
from student.models import Student, Parent
# Create your views here.

class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    fields = [
            'name', 
            'select_class'
            ]
    def form_valid(self, form):
        form.instance.course_code = id_generator()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            # 'object': Course.objects.get(slug=self.kwargs.get('slug')),
            'courses':Course.objects.all().order_by('-id'),
            'classes':Class.objects.all()
        })  
        return context
    def get_success_url(self):
        return reverse('create')


@login_required
def dashboard(request):
    students = Student.objects.all()

    student_count = 0
    for item in students:
        student_count += 1
    
    parents = Parent.objects.all()

    parent_count=0
    for _ in parents:
        parent_count+=1
    context={
        'student_count':student_count,
        'parent_count':parent_count
    }
    return render(request, 'dashboard.html', context)

templates/course/course_form.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
  All Students
{% endblock title %}
  

{% block cou %}
    active
{% endblock cou %}
    

{% block top %}
   <a  style="color: turquoise;"> Courses</a>
{% endblock top %}

{% load humanize %}

{% block content %}  
  
      <div class="content">
        <div class="row">
            <div class="col-md-12">
              {% include 'alerts.html' %}
              <div class="card">
                <div class="card-header ">
                  <h6 class="title d-inline"> <strong>Add New Course</strong></h6>
                </div>
                <div class="card-body">
                  <form method = "POST">
                    {% include 'form_errors.html' %}
                    {% csrf_token %}
                    <div class="row">
                      <div class="col-md-4 pr-md-1">
                        <div class="form-group">
                          <label for="id_name">Course Name *</label>
                          <input type="text" name="name" class="form-control" maxlength="120" required="" id="id_name">
                        </div>
                      </div>
                      <div class="col-md-4 px-md-1">
                        <div class="form-group">
                          <label for="id_select_class">Select class:</label>
                            <select name="select_class" required="" class="form-control" id="id_select_class">
                            <option value="" selected="">---------</option>
                            {% for class in classes %}
                            <option value="{{ class.id }}">{{class.name}}</option>
                            {% endfor %}
                          
                          </select>
                        </div>
                      </div>
                      <div class="col-md-4 pl-md-1">
                        <div class="form-group"><br>
                            <input type="submit" class="btn btn-fill btn-primary" value="Create">
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card card-tasks">
              <div class="card-header ">
                <h6 class="title d-inline"> <strong> All Courses Data</strong></h6>
              </div>
              <div class="card-body ">
                <div class="table-full-width table-responsive">
                  <table class="table">
                    <thead class=" text-primary">
                        <tr>
                          <th>
                            <div class="form-check">
                                <label class="form-check-label">
                                  <input class="form-check-input" type="checkbox" checked value="">
                                  <span class="form-check-sign">
                                    <span class="check"></span>
                                  </span>
                                </label>
                              </div>
                          </th>
                          <th>
                            Course Code
                          </th>
                          <th>
                            Course Name
                          </th>
                          <th>
                            Class
                          </th>
                          <th>
                            Creation Date & Time
                          </th>
                        </tr>
                      </thead>
                    <tbody>
                    {% if courses %}
                    {% for course in courses %}
                      <tr>
                        <td>
                          <div class="form-check">
                            <label class="form-check-label">
                              <input class="form-check-input" type="checkbox" value="">
                              <span class="form-check-sign">
                                <span class="check"></span>
                              </span>
                            </label>
                          </div>
                        </td>
                        <td>
                          <p class="title">{{ course.course_code }}</p>
                        </td>
                        <td>
                          <p class="title">{{ course.name }}</p>
                        </td>
                        <td>
                          <p class="title">{{course.select_class}}</p>
                        </td>
                        <td>
                          <p>{{course.date_stamp}}</p>
                        </td>
                      </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                      <td colspan="4"> 
                        There are no courses available yet. Create a course to get started.
                      </td>
                    </tr>
                    {% endif %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}