course/urls.py
from django.urls import path
from .views import CourseCreateView
urlpatterns = [
    path('create-course/', CourseCreateView.as_view(), name='create'),
]

schoolmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from course.views import dashboard

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard, name='dashboard'),
    path('', include('course.urls')),
    path('', include('student.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
]

admin.site.site_header = "Green Sprouts Admin"
admin.site.site_title = "Green SProuts Management Portal"
admin.site.index_title = "Welcome to Green Sprouts Management Portal"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from .views import (
    student_admmision, 
    add_parent,
    StudentListView, 
    StudentDetailView,
    StudentUpdateView,
    ParentListView,
    ParentDetailView,
    ParentUpdateView,
    search,
    search_parent
    )
urlpatterns = [
    path('student-admission/', student_admmision, name='admission'),
    path('add-parent/', add_parent, name='add_parent'),
    path('all-parents/', ParentListView.as_view(), name='all_parent'),
    path('all-students/', StudentListView.as_view(), name='all_student'),
    path('students/<slug>', StudentDetailView.as_view(), name='student'),
    path('students/<slug>/update', StudentUpdateView.as_view(), name='update-student'),
    path('parents/<slug>', ParentDetailView.as_view(), name='parent'),
    path('parents/<slug>/update', ParentUpdateView.as_view(), name='update-parent'),
    path('search/', search, name='search'),
    path('parents/search/', search_parent, name='search_parent'),
]

student/models.py
from django.db import models

from django.utils.text import slugify
from django.urls import reverse
from course.models import Class
# Create your models here.

GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female')
)

CLASS_CHOICES = (
    ('JSS 1 ', 'JSS 1'),
    ('JSS 2', 'JSS 2'),
    ('JSS 3', 'JSS 3'),
    ('SSS 1', 'SSS 1'),
    ('SSS 2', 'SSS 2'),
    ('SSS 3', 'SSS 3')
)


class Student(models.Model):
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES)
    date_of_birth = models.DateField()
    blood_group = models.CharField(max_length=50)
    religion = models.CharField(max_length=50)
    email = models.EmailField()
    student_class = models.ForeignKey(Class,on_delete=models.SET_NULL, null=True,default='Please Select Class *')
    admission_id = models.CharField(max_length=120, default='ABC', unique=True)
    phone = models.CharField(max_length=50)
    short_BIO = models.TextField(blank=True, null=True)
    upload_student_photo = models.ImageField(default='default.png', upload_to='student_photo/')
    slug = models.SlugField(
        default='',
        editable=False,
        max_length=120,
    )
    date_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_name
      

    class Meta:
        unique_together = ('first_name', 'slug')

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug
        }
        return reverse('student', kwargs=kwargs)

    def save(self, *args, **kwargs):
        value = self.first_name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

class Parent(models.Model):
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES)
    occupation = models.CharField(max_length=50)
    ward = models.ManyToManyField(Student, blank=True)
    blood_group = models.CharField(max_length=50)
    religion = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    phone = models.CharField(max_length=50)
    short_BIO = models.TextField(blank=True, null=True)
    upload_parent_photo = models.ImageField(default='default.png', upload_to='parent_photo/')
    slug = models.SlugField(
        default='',
        editable=False,
        max_length=120,
    )
        
    def __str__(self):
        return self.first_name
    
    

    class Meta:
        unique_together = ('first_name', 'slug')

    def get_absolute_url(self):
        kwargs = {
            'slug': self.slug
        }
        return reverse('parent', kwargs=kwargs)

    def save(self, *args, **kwargs):
        value = self.first_name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

student/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Student, Parent

User = get_user_model()

class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First name')
    last_name = forms.CharField(max_length=30, label='Last name')

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

class StudentUpdateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'first_name', 
            'last_name', 
            'gender',
            'date_of_birth',
            'blood_group',
            'religion', 
            'email',
            'student_class',
            'phone',
            'short_BIO',
            'upload_student_photo'
            ]

class ParentUpdateForm(forms.ModelForm):
    class Meta:
        model = Parent
        fields = [
            'first_name', 
            'last_name', 
            'gender',
            'occupation',
            'ward',
            'blood_group',
            'religion', 
            'email',
            'address',
            'phone',
            'short_BIO',
            'upload_parent_photo'
            ]

student/views.py
from django.shortcuts import render, redirect
from .utils import id_generator
from .models import Student, Parent
from .forms import StudentUpdateForm, ParentUpdateForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, UpdateView
from course.models import Course, Class
# Create your views here.

@login_required
def student_admmision(request):
    if request.method == 'POST':
        p_form = StudentUpdateForm(
            request.POST, 
            request.FILES 
            )

        if p_form.is_valid():
            new_admmision = p_form.save(commit=False)
            new_admmision.admission_id = id_generator()
            new_admmision.save()
            messages.success(
                request, 'You have successfully added a new student!'
                )
            return redirect('all_student')
    else:
        p_form = StudentUpdateForm()
    classes = Class.objects.all()
    return render(request, 'student/admission.html', {'p_form':p_form, 'classes':classes})

class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    context_object_name = 'students'
    ordering = ['-id']
    paginate_by = 15

class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'courses': Course.objects.all(),
            # 'class': Class.objects.get(),
        })  
        return context


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Student
    fields = [
            'first_name', 
            'last_name', 
            'gender',
            'date_of_birth',
            'blood_group',
            'religion', 
            'email',
            'student_class',
            'phone',
            'short_BIO',
            'upload_student_photo'
            ]
    template_name = 'student/admission.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'object': Student.objects.get(slug=self.kwargs.get('slug')),
        })  
        return context

def add_parent(request):
    students = Student.objects.all()
    if request.method == 'POST':
        p_form = ParentUpdateForm(
            request.POST, 
            request.FILES 
            )

        if p_form.is_valid():
            p_form.save()
            messages.success(
                request, 'You have successfully added a new parent!'
                )
            return redirect('add_parent')
    else:
        p_form = ParentUpdateForm()
    
    context = {
        'p_form':p_form, 
        'students':students
        } 
    return render(request, 'student/add_parent.html', context)

class ParentListView(LoginRequiredMixin, ListView):
    model = Parent
    context_object_name = 'parents'
    ordering = ['-id']
    paginate_by = 4

class ParentDetailView(LoginRequiredMixin, DetailView):
    model = Parent

class ParentUpdateView(LoginRequiredMixin, UpdateView):
    model = Parent
    fields = [
            'first_name', 
            'last_name', 
            'gender',
            'occupation',
            'ward',
            'blood_group',
            'religion', 
            'email',
            'address',
            'phone',
            'short_BIO',
            'upload_parent_photo'
            ]
    template_name = 'student/add_parent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'object': Parent.objects.get(slug=self.kwargs.get('slug')),
            'students': Student.objects.all().order_by('-id')
        })  
        return context

def search(request):
    if request.method == 'GET':
        admission_id = request.GET['admission_id']
        name = request.GET['name']
        student_class = request.GET['class']
        if admission_id == '':
            admission_id = 'none'
        if name == '':
            name = 'none'
        if student_class == '':
            student_class = 'none'

        result = Student.objects.filter(admission_id__icontains=admission_id)|Student.objects.filter(first_name__icontains = name)|Student.objects.filter(student_class__icontains=student_class)

        context = {
            'result':result,
            'admission_id':admission_id,
            'name':name,
            'student_class':student_class
        }
        return render(request, 'student/search.html', context)


def search_parent(request):
    if request.method == 'GET':
        phone = request.GET['phone']
        name = request.GET['name']
        occupation = request.GET['occupation']
        if phone == '':
            phone = 'none'
        if name == '':
            name = 'none'
        if occupation == '':
            occupation = 'none'

        result = Parent.objects.filter(phone__icontains=phone)|Parent.objects.filter(first_name__icontains = name)|Parent.objects.filter(occupation__icontains=occupation)

        context = {
            'result':result,
        }
        return render(request, 'student/search-parent.html', context)

templates/student/add_parent.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Students
{% endblock title %}


{% block par %}
  active
{% endblock par %}

{% block top %}
    Parents  
{% endblock top %}

{% block content %}

    
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            {% include 'alerts.html' %}
            <div class="card">
              <div class="card-header">
                <h5 class="title">Add New Parent</h5>
              </div>
              <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                  {% include 'form_errors.html' %}
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-md-4 pr-md-1">
                      <div class="form-group">
                        <label for="id_first_name">First name *</label>
                        <input type="text" name="first_name" maxlength="120" value="{{ object.first_name }}" class="form-control" required="" id="id_first_name">
                      </div>
                    </div>
                    <div class="col-md-4 px-md-1">
                      <div class="form-group">
                        <label for="id_last_name">Last name *</label> 
                        <input type="text" name="last_name" class="form-control" value="{{ object.last_name }}" maxlength="120" required="" id="id_last_name">
                      </div>
                    </div>
                    <div class="col-md-4 pl-md-1">
                      <div class="form-group">
                        <label for="id_gender">Gender *</label>
                        <select name="gender" class="form-control" required="" id="id_gender">
                          <option value="" selected="">Please Select Gender *</option>
                        
                          <option value="Male">Male</option>
                        
                          <option value="Female">Female</option>
                        
                        </select>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-4 pr-md-1">
                      <div class="form-group">
                        <label for="id_occupation">Occupation *</label>
                        <input type="text" class="form-control" name="occupation" value="{{ object.occupation }}" maxlength="50" required="" id="id_occupation">
                      </div>
                    </div>
                    <div class="col-md-4 px-md-1">
                      <div class="form-group">
                        <label for="id_ward">Ward *</label> 
                          <select name="ward" class="form-control" required id="id_ward" style="margin-bottom: 0px;" multiple="">
                            {% for student in students %}
                              <option value="{{ student.id }}">{{ student.first_name }} {{ student.last_name }}</option>
                            {% endfor %}
                          </select>
                        <span><small class="text-info">You can select more than one. Hold CTRL or Command on Mac</small></span>
                      </div>
                    </div>
                    <div class="col-md-4 pl-md-1">
                      <div class="form-group">
                        <label for="id_blood_group">Blood group:</label>
                        <input type="text" name="blood_group" class="form-control" value="{{ object.blood_group }}" maxlength="50" required="" id="id_blood_group">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-4 pr-md-1">
                      <div class="form-group">
                        <label for="id_religion">Religion *</label>
                        <input type="text" name="religion" class="form-control" maxlength="50" value="{{ object.religion }}" required="" id="id_religion">
                      </div>
                    </div>
                    <div class="col-md-4 px-md-1">
                      <div class="form-group">
                        <label for="id_email">Email *</label>
                        <input type="email" class="form-control" name="email" value="{{ object.email }}" placeholder="someone@email.com" maxlength="254" required="" id="id_email">
                      </div>
                    </div>
                    <div class="col-md-4 pl-md-1">
                      <div class="form-group">
                        <label for="id_phone">Phone *</label>
                        <input type="text" class="form-control" name="phone" value="{{ object.phone }}" maxlength="50" required="" id="id_phone">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label for="id_address">Address *</label>
                        <input type="text" name="address" class="form-control" value="{{ object.address }}"  maxlength="150" required="" id="id_address">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-8">
                      <div class="form-group">
                        <label for="id_short_BIO">Short BIO *</label>
                        <textarea name="short_BIO" cols="80" rows="4" class="form-control" id="id_short_BIO">{{ object.short_BIO }}</textarea>
                      </div>
                    </div>
                    <div class="col-md-4 pl-md-1">
                      <div class="">
                        <label for="id_upload_parent_photo">Upload parent photo *</label><br>
                        {% if object.upload_parent_photo %}
                        <small>
                          Currently: <a href="{{ object.upload_parent_photo.url }}">{{ object.upload_parent_photo }}</a>
                        </small>
                        {% endif %}
                        <input type="file" name="upload_parent_photo" accept="image/*" id="id_upload_parent_photo">
                      </div>
                    </div>
                  </div>
                  <div class="card-footer">
                    <button type="submit" class="btn btn-fill btn-primary">Save</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

templates/student/admission.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Students
{% endblock title %}


{% block stu %}
  active
{% endblock stu %}

{% block top %}
    Students  
{% endblock top %}

{% block content %}

    
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            {% include 'alerts.html' %}
            <div class="card">
              <div class="card-header">
                <h5 class="title">Add New Student</h5>
              </div>
              <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                  {% include 'form_errors.html' %}
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-md-4 pr-md-1">
                      <div class="form-group">
                        <label for="id_first_name">First name *</label>
                        <input type="text" name="first_name" value="{{object.first_name}}" maxlength="120" class="form-control" placeholder="First Name" required="" id="id_first_name">
                      </div>
                    </div>
                    <div class="col-md-4 px-md-1">
                      <div class="form-group">
                        <label for="id_last_name">Last name *</label>
                        <input type="text" name="last_name" value="{{ object.last_name }}" maxlength="120" class="form-control" placeholder="Last Name" required="" id="id_last_name">
                      </div>
                    </div>
                    <div class="col-md-4 pl-md-1">
                      <div class="form-group">
                        <label for="id_gender">Gender *</label>
                        <select name="gender" class="form-control" required="" id="id_gender">
                          <option value="" selected="">Please Select Gender *</option>
                        
                          <option value="Male">Male</option>
                        
                          <option value="Female">Female</option>
                        
                        </select>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-4 pr-md-1">
                      <div class="form-group">
                        <label for="id_date_of_birth">Date of birth *</label>
                        <input type="date" class="form-control" value="{{object.date_of_birth}}" name="date_of_birth" required="" id="id_date_of_birth">
                      </div>
                    </div>
                    <div class="col-md-4 px-md-1">
                      <div class="form-group">
                        <label for="id_blood_group">Blood group *</label>
                        <input type="text" class="form-control" value="{{ object.blood_group }}" name="blood_group" maxlength="50" required="" id="id_blood_group">
                      </div>
                    </div>
                    <div class="col-md-4 pl-md-1">
                      <div class="form-group">
                        <label for="id_religion">Religion *</label>
                        <input type="text" name="religion" class="form-control" value="{{ object.religion }}" maxlength="50" required="" id="id_religion">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-4 pr-md-1">
                      <div class="form-group">
                        <label for="id_email">Email *</label>
                        <input type="email" class="form-control" name="email" value="{{ object.email }}" placeholder="someone@email.com" maxlength="254" required="" id="id_email">
                      </div>
                    </div>
                    <div class="col-md-4 px-md-1">
                      <div class="form-group">
                        <label for="id_student_class">Student class:</label>
                        <select name="student_class" required class="form-control" id="id_student_class">
                          {% for class in classes %}
                          <option value="{{ class.id }}">{{ class.name }}</option>
                          {% endfor %}
                        
                        </select>
                      </div>
                    </div>
                    <div class="col-md-4 pl-md-1">
                      <div class="form-group">
                        <label for="id_phone">Phone *</label>
                        <input type="text" class="form-control" value="{{ object.phone }}" name="phone" maxlength="50" required="" id="id_phone">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-8">
                      <div class="form-group">
                        <label for="id_short_BIO">Short BIO *</label>
                        <textarea name="short_BIO" cols="80" rows="4" class="form-control" id="id_short_BIO">{{ object.short_BIO }}</textarea>
                      </div>
                    </div>
                    <div class="col-md-4 pl-md-1">
                      <div class="">
                        <label for="id_upload_student_photo">Upload student photo *</label> <br>
                        {% if object.upload_student_photo %} 
                        <small>Currently: <a href="{{ object.upload_student_photo.url }}">{{ object.upload_student_photo }}</a></small>
                        {% endif %}
                        <input type="file" name="upload_student_photo" accept="image/*" id="id_upload_student_photo">
                      </div>
                    </div>
                  </div>
                  <div class="card-footer">
                    <button type="submit" class="btn btn-fill btn-primary">Save</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

templates/student/all_students.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
  All Students
{% endblock title %}
  

{% block stu %}
    active
{% endblock stu %}
    

{% block top %}
   <a  style="color: turquoise;"> Students</a>
{% endblock top %}

{% load humanize %}

{% block content %}  
  
      <div class="content">
        <div class="row">
            <div class="col-md-12">
              {% include 'alerts.html' %}
              <div class="card">
                <div class="card-body">
                  <form action="{% url 'search' %}">
                    {% include 'form_errors.html' %}
                    {% csrf_token %}
                    <div class="row">
                      <div class="col-md-3 pr-md-1">
                        <div class="form-group">
                          <input type="search" name="admission_id" maxlength="120" class="form-control" placeholder="Search by admission id" >
                        </div>
                      </div>
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <input type="search" name="name" maxlength="120" class="form-control" placeholder="Search by Name" id="id_last_name">
                        </div>
                      </div>
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <input type="search" name="class" placeholder="Search by Class" class="form-control" >
                        </div>
                      </div>
                      <div class="col-md-3 pl-md-1">
                        <div class="form-group">
                            <input type="submit" class="btn btn-fill btn-primary" value="Search">
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="card card-tasks">
              <div class="card-header ">
                <h6 class="title d-inline"> <strong> All Students Data</strong></h6>
                <div class="dropdown">
                  <button type="button" class="btn btn-link dropdown-toggle btn-icon" data-toggle="dropdown">
                    <i class="tim-icons icon-settings-gear-63"></i>
                  </button>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'admission' %}">Add Student</a>
                    <a class="dropdown-item" href="">All Parents</a>
                    <a class="dropdown-item" href="{% url 'add_parent' %}">Add Parent</a>
                  </div>
                </div>
              </div>
              <div class="card-body ">
                <div class="table-full-width table-responsive">
                  <table class="table">
                    <thead class=" text-primary">
                        <tr>
                          <th>
                            <div class="form-check">
                                <label class="form-check-label">
                                  <input class="form-check-input" type="checkbox" checked value="">
                                  <span class="form-check-sign">
                                    <span class="check"></span>
                                  </span>
                                </label>
                              </div>
                          </th>
                          <th>
                            Admission Id
                          </th>
                          <th>
                            Photo
                          </th>
                          <th>
                            Name
                          </th>
                          <th>
                            Gender
                          </th>
                          <th>
                            Class
                          </th>
                          <th>
                            Parents
                          </th>
                          <th>
                            Address
                          </th>
                          <th>
                            Date of birth
                          </th>
                          <th>
                            Phone
                          </th>
                          <th>
                            E-mail
                          </th>
                        </tr>
                      </thead>
                    <tbody>
                    {% for student in students %}
                      <tr>
                        <td>
                          <div class="form-check">
                            <label class="form-check-label">
                              <input class="form-check-input" type="checkbox" value="">
                              <span class="form-check-sign">
                                <span class="check"></span>
                              </span>
                            </label>
                          </div>
                        </td>
                        <td>
                          <p class="title">#{{ student.admission_id }}</p>
                        </td>
                        <td class="td-actions text-right">
                          <img src="{{student.upload_student_photo.url}}" alt=""> 
                        </td>
                        <td>
                          <p class="title">{{student.first_name}}</p>
                          <p class="text-muted">{{ student.last_name }}</p>
                        </td>
                        <td>
                          <p>{{student.gender}}</p>
                        </td>
                        <td>
                          <p class="title">{{ student.student_class }}</p>
                        </td>
                        <td>
                            {% if student.parent_set.all %}
                            {% for parent in student.parent_set.all %}
                                <p>{{ parent.first_name }}</p>
                            {% endfor %}
                            {% else %}
                                <p>---</p>
                            {% endif %}
                        </td>
                        <td class="">
                            {% if student.parent_set.all %}
                            {% for parent in student.parent_set.all %}
                                <p>{{ parent.address|truncatewords:2 }}</p>
                            {% endfor %}
                            {% else %}
                                <p>---</p>
                            {% endif %}
                        </td>
                        <td>
                          <p>{{ student.date_of_birth }}</p>
                        </td>
                        <td>
                          <p>{{ student.phone }}</p>
                        </td>
                        <td>
                          <p>{{ student.email }}</p>
                        </td>
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}